/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./renderer.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary": "#303030",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#a6c8ff",
        "secondary-fixed-dim": "#c8c6c6",
        "primary": "#a6c8ff",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#e4e2e1",
        "tertiary": "#c8c6c6",
        "on-error": "#690005",
        "on-primary": "#003060",
        "secondary": "#c8c6c6",
        "surface-variant": "#353534",
        "on-secondary": "#303030",
        "background": "#131313",
        "surface": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#c1c6d4",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary-container": "#dbe7ff",
        "tertiary-container": "#686767",
        "primary-container": "#0067c0",
        "on-error-container": "#ffdad6",
        "surface-tint": "#a6c8ff",
        "secondary-fixed": "#e4e2e1",
        "outline": "#8b919d",
        "surface-container-highest": "#353534",
        "tertiary-fixed-dim": "#c8c6c6",
        "error-container": "#93000a",
        "outline-variant": "#414752",
        "on-secondary-fixed-variant": "#474747",
        "inverse-primary": "#005eb1",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#b6b5b4",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#004787",
        "primary-fixed": "#d5e3ff",
        "on-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "on-primary-fixed": "#001c3b",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#e8e6e5",
        "secondary-container": "#474747",
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#1b1c1c",
        "error": "#ffb4ab"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
